### ISSUE TITLE
Project Broken after update android studio and gradle version

### ISSUE THREAD

**Issue by steelxtreme** [requery/requery#467]
hello, I was using requery succesfully after an android tools and gradle update, now can't generate classes:
I've tried everything.

this is my console output after full rebuild:

`
Executing tasks: [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:compileDebugSources, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/devquilla/Android/Sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

:clean
:app:clean
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidDatabindingAdapters131Library
:app:prepareComAndroidDatabindingLibrary131Library
:app:prepareComAndroidSupportAnimatedVectorDrawable2520Library
:app:prepareComAndroidSupportAppcompatV72520Library
:app:prepareComAndroidSupportSupportCompat2520Library
:app:prepareComAndroidSupportSupportCoreUi2520Library
:app:prepareComAndroidSupportSupportCoreUtils2520Library
:app:prepareComAndroidSupportSupportFragment2520Library
:app:prepareComAndroidSupportSupportMediaCompat2520Library
:app:prepareComAndroidSupportSupportV42520Library
:app:prepareComAndroidSupportSupportVectorDrawable2520Library
:app:prepareIoReactivexRxandroid121Library
:app:prepareIoRequeryRequeryAndroid120Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:dataBindingProcessLayoutsDebug
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:preDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportTestEspressoEspressoCore222Library
:app:prepareComAndroidSupportTestEspressoEspressoIdlingResource222Library
:app:prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library
:app:prepareComAndroidSupportTestRules05Library
:app:prepareComAndroidSupportTestRunner05Library
:app:prepareDebugAndroidTestDependencies
:app:compileDebugAndroidTestAidl
:app:processDebugAndroidTestManifest
:app:compileDebugAndroidTestRenderscript UP-TO-DATE
:app:generateDebugAndroidTestBuildConfig
:app:generateDebugAndroidTestResValues
:app:generateDebugAndroidTestResources
:app:mergeDebugAndroidTestResources
:app:processDebugAndroidTestResources
:app:generateDebugAndroidTestSources
:app:mockableAndroidJar
:app:preDebugUnitTestBuild UP-TO-DATE
:app:prepareDebugUnitTestDependencies
:app:dataBindingExportBuildInfoDebug
:app:incrementalDebugJavaCompilationSafeguard
:app:javaPreCompileDebug
:app:transformClassesAndDataBindingWithDataBindingMergeArtifactsForDebug
:app:compileDebugJavaWithJavac
/home/devquilla/AndroidStudioProjects/Wayuu/app/build/generated/source/apt/debug/main/zlab/com/wayuu/repository/model/DictionaryEntity.java:235: error: cannot find symbol
        notifyPropertyChanged(main.zlab.com.wayuu.repository.model.BR.word);
                                                                  ^
  symbol:   class BR
  location: package main.zlab.com.wayuu.repository.model
/home/devquilla/AndroidStudioProjects/Wayuu/app/build/generated/source/apt/debug/main/zlab/com/wayuu/repository/model/DictionaryEntity.java:246: error: cannot find symbol
        notifyPropertyChanged(main.zlab.com.wayuu.repository.model.BR.definition);
                                                                  ^
  symbol:   class BR
  location: package main.zlab.com.wayuu.repository.model
/home/devquilla/AndroidStudioProjects/Wayuu/app/build/generated/source/apt/debug/main/zlab/com/wayuu/repository/model/DictionaryEntity.java:257: error: cannot find symbol
        notifyPropertyChanged(main.zlab.com.wayuu.repository.model.BR.letra);
                                                                  ^
  symbol:   class BR
  location: package main.zlab.com.wayuu.repository.model
3 errors

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.578 secs

`

also after --info i did notice:

`
Executing task ':app:compileDebugJavaWithJavac' (up-to-date check took 0.004 secs) due to:
  No history is available.
All input files are considered out-of-date for incremental task ':app:compileDebugJavaWithJavac'.
Compiling with source level 1.7 and target level 1.7.
file or directory '/home/devquilla/AndroidStudioProjects/Wayuu/app/src/debug/java', not found
file or directory '/home/devquilla/AndroidStudioProjects/Wayuu/app/build/generated/source/rs/debug', not found
Compiling with JDK Java compiler API.

`

Any help would be appreciated.

**Comment by npurushe** [comment]
Looks like your Android data binding class BR wasn't generated. Do you maybe have an error in your layout binding expressions?

**Comment by kusyjan** [comment]
I have got same problem. I before android studio update and gradle update everything works fine, but when I update gradle to 3.3, requery won't generate BR class as @npurushe says.

**Comment by Seidak** [comment]
Hello I had the same problem, we have example project using data binding and after update we weren't able to build project anymore.

It looks like generated BR class is placed to different location than entity class. Because of that we are failing the build. Generated path to BR class cannot be resolved.

**Comment by npurushe** [comment]
Can you specify what version of the android gradle plugin you update to that is causing the problem?  thanks

**Comment by steelxtreme** [comment]
yeah, I know that BR class weren't generated, but happened after update build tools to 25.0.2 and gradle 3.3

**Comment by npurushe** [comment]
Did you also change the android gradle plugin version? I've tried 25.0.2 and gradle 3.4 with no issues, the gradle version shouldn't really affect it

**Comment by steelxtreme** [comment]
I had tried with gradle 3.4 with not success 

here is my gradle config 

`apply plugin: 'com.android.application'



android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'
    defaultConfig {
        applicationId "main.zlab.com.wayuu"
        minSdkVersion 22
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
//        jackOptions {
//            enabled true
//        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
        disable 'InvalidPackage'
    }

//    compileOptions {
//        sourceCompatibility JavaVersion.VERSION_1_8
//        targetCompatibility JavaVersion.VERSION_1_8
//    }
    dataBinding {
        enabled = true
    }
    sourceSets { main { assets.srcDirs = ['src/main/assets', 'src/main/res/assets/'] } }
    productFlavors {
    }
}


dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:support-annotations:25.2.0'
    compile 'com.android.databinding:compiler:2.3.0'
    testCompile 'junit:junit:4.12'
    compile "io.reactivex:rxjava:1.2.0"

    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.requery:requery:1.2.0'
    compile 'io.requery:requery-android:1.2.0'
    // for android
    annotationProcessor 'io.requery:requery-processor:1.2.0'
    compile 'com.android.support:support-annotations:25.2.0'
    compile 'com.android.support:appcompat-v7:25.2.0'
}

`
and gradle wrapper

`#Thu Mar 09 21:54:52 COT 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-3.4-all.zip
`

**Comment by steelxtreme** [comment]
I had tried with gradle 3.4 with not success 

here is my gradle config 

`apply plugin: 'com.android.application'



android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'
    defaultConfig {
        applicationId "main.zlab.com.wayuu"
        minSdkVersion 22
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
//        jackOptions {
//            enabled true
//        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
        disable 'InvalidPackage'
    }

//    compileOptions {
//        sourceCompatibility JavaVersion.VERSION_1_8
//        targetCompatibility JavaVersion.VERSION_1_8
//    }
    dataBinding {
        enabled = true
    }
    sourceSets { main { assets.srcDirs = ['src/main/assets', 'src/main/res/assets/'] } }
    productFlavors {
    }
}


dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:support-annotations:25.2.0'
    compile 'com.android.databinding:compiler:2.3.0'
    testCompile 'junit:junit:4.12'
    compile "io.reactivex:rxjava:1.2.0"

    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.requery:requery:1.2.0'
    compile 'io.requery:requery-android:1.2.0'
    // for android
    annotationProcessor 'io.requery:requery-processor:1.2.0'
    compile 'com.android.support:support-annotations:25.2.0'
    compile 'com.android.support:appcompat-v7:25.2.0'
}

`
and gradle wrapper

`#Thu Mar 09 21:54:52 COT 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-3.4-all.zip
`

**Comment by npurushe** [comment]
What's the package your BR file is generated in?

**Comment by steelxtreme** [comment]
hi, this is the package

main.zlab.com.wayuu.repository.model

**Comment by steelxtreme** [comment]
I'm still facing this issue, any clue how to resolve it?

**Comment by steelxtreme** [comment]
Update:  I found BR class was generated at  main.zlab.com.wayuu and DictionaryEndity class have a reference to : main.zlab.com.wayuu.repository.model.BR

Different packages.

**Comment by indiv0** [comment]
I'm having this issue as well, with the same symptoms. The `BR` class file is being generated in the root module, and not the `model` submodule (in my case).

**Comment by npurushe** [comment]
This is caused by upgrading to Android gradle plugin 2.3 (com.android.tools.build:gradle:2.3.0). 

In previous versions of the plugin the databinding package name (where the BR file is generated) was provided on an annotation in a generate file. In the new version it's passed as a annotation processor option which is now handled.

An updated version will be available soon, a temporary workaround is to simply use the previous android gradle plugin 2.2.2

**Comment by steelxtreme** [comment]
Was Solved by adding in gradle

`  lintOptions {
        abortOnError false
        disable 'InvalidPackage'
    }`

and in proguard file :

-keep class * extends java.lang.Enum {
}
-dontwarn rx.internal.**
-dontwarn android.support.**

All based in latest android example in repo.

best regards.

**Comment by xorander00** [comment]
Any update on this issue?  I see the code change from alex-shpak.

**Comment by consp1racy** [comment]
Hello @xorander00, If there were any updates on the issue ***THEY WOULD BE POSTED HERE***.

**Comment by xorander00** [comment]
@consp1racy Just pinging for a status update because I'm going to make some local changes and didn't want to waste time doing duplicate work.  No harm, no foul.

Also, I work weekends.

**Comment by npurushe** [comment]
version 1.3.0 contains this fix

**Comment by xorander00** [comment]
Excellent!  I just updated and it looks to be working fine.  Great work, loving the project man :)

Quick & dumb question, but...when performing a query using EntityDataStore, does it automatically return the connection to the pool or does my code need to be explicit about that?

I'm using requery on both my Java server-side project as well as client-side Android project.  It's working fine on Android, but on my server project it exhausts the connection pool after running for a while.  It looks like none of the connections are being returned, so I'm wondering what it is that I'm missing.
