### ISSUE TITLE
1.6.1 crash on new DatabaseSource

### ISSUE THREAD

**Issue by Crisaldroid** [requery/requery#877]
Since I updated requery from version 1.5.1 to 1.6.1, it make my app crash on startup : 

Process: my.app.dot.prod, PID: 11168
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at io.requery.android.sqlite.DatabaseSource.<init>(DatabaseSource.kt)
        [...]
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[....],nativeLibraryDirectories=[/data/app/my.app.dot.prod-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at io.requery.android.sqlite.DatabaseSource.<init>(DatabaseSource.kt)
        [...]
